module.exports = [
    { title: "Forest Retreat" },
    { title: "Mountain View Camp" },
    { title: "Riverside Escape" },
    { title: "Sunny Meadows" },
    { title: "Lakeview Campground" },
    { title: "Pine Woods" },
    { title: "Desert Oasis" },
    { title: "Coastal Breeze Camp" },
    { title: "Valley Hideout" },
    { title: "Hilltop Camp" },
    { title: "Red Rock Camp" },
    { title: "Wildflower Haven" },
    { title: "Blue Sky Camp" },
    { title: "Golden Sands Camp" },
    { title: "Cedar Grove" },
    { title: "Whispering Pines" },
    { title: "Hidden Creek Camp" },
    { title: "Starlight Basecamp" },
    { title: "Oak Ridge Camp" },
    { title: "Evergreen Escape" },
    { title: "Silver Lake Camp" },
    { title: "Tranquil Shores" },
    { title: "Horizon Campground" },
    { title: "Shadow Valley" },
    { title: "Sunny Ridge Camp" },
    { title: "Timberline Camp" },
    { title: "Rocky Path Camp" },
    { title: "Serenity Springs" },
    { title: "Canyon Edge Camp" },
    { title: "Prairie Creek Camp" },
    { title: "Highland Camp" },
    { title: "Morning Mist Camp" },
    { title: "Ridgeview Camp" },
    { title: "Breezy Point" },
    { title: "Moonlight Campground" },
    { title: "Granite Falls Camp" },
    { title: "Autumn Woods" },
    { title: "Clearwater Camp" },
    { title: "Shady Hollow" },
    { title: "Crimson Peak Camp" },
    { title: "Open Sky Camp" },
    { title: "Blue Ridge Camp" },
    { title: "Wild Canyon Camp" },
    { title: "Northern Lights Base" },
    { title: "Rustic Pines" },
    { title: "Sunset Ridge Camp" },
    { title: "Rolling Hills Camp" },
    { title: "Quiet Valley Camp" },
    { title: "Maple Springs" },
    { title: "Green Haven Camp" },
    { title: "Silver Birch Camp" }
];
